language: python
dist: bionic

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=behave-14.04
      script:
          # bionic has lxd from deb installed, remove it first to avoid
          # confusion over versions
          - BUILD_PR=1
          - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then BUILD_PR=0; fi
          - >
              if [ "$BUILD_PR" -eq "1" ]; then
                 cd $TRAVIS_BUILD_DIR/..
                 tar -zcvf pr_source.tar.gz ubuntu-advantage-client
                 cp pr_source.tar.gz /tmp
                 ls -lh /tmp
                 cd $TRAVIS_BUILD_DIR
                 pwd
              fi
          - sudo apt-get remove --yes --purge lxd lxd-client
          - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - sg lxd -c "UACLIENT_BEHAVE_BUILD_PR=${BUILD_PR} make test"
    - python: 3.7
      env: TOXENV=behave-16.04
      script:
          # bionic has lxd from deb installed, remove it first to avoid
          # confusion over versions
          - BUILD_PR=1
          - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then BUILD_PR=0; fi
          - >
              if [ "$BUILD_PR" -eq "1" ]; then
                 cd $TRAVIS_BUILD_DIR/..
                 tar -zcvf pr_source.tar.gz ubuntu-advantage-client
                 cp pr_source.tar.gz /tmp
                 ls -lh /tmp
                 cd $TRAVIS_BUILD_DIR
                 pwd
              fi
          - sudo apt-get remove --yes --purge lxd lxd-client
          - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - sg lxd -c "UACLIENT_BEHAVE_BUILD_PR=${BUILD_PR} make test"
    - python: 3.7
      env: TOXENV=behave-18.04
      script:
          # bionic has lxd from deb installed, remove it first to avoid
          # confusion over versions
          - BUILD_PR=1
          - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then BUILD_PR=0; fi
          - >
              if [ "$BUILD_PR" -eq "1" ]; then
                 cd $TRAVIS_BUILD_DIR/..
                 tar -zcvf pr_source.tar.gz ubuntu-advantage-client
                 cp pr_source.tar.gz /tmp
                 ls -lh /tmp
                 cd $TRAVIS_BUILD_DIR
                 pwd
              fi
          - sudo apt-get remove --yes --purge lxd lxd-client
          - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - sg lxd -c "UACLIENT_BEHAVE_BUILD_PR=${BUILD_PR} make test"
    - python: 3.7
      env: TOXENV=behave-20.04
      script:
          # bionic has lxd from deb installed, remove it first to avoid
          # confusion over versions
          - BUILD_PR=1
          - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then BUILD_PR=0; fi
          - >
              if [ "$BUILD_PR" -eq "1" ]; then
                 cd $TRAVIS_BUILD_DIR/..
                 tar -zcvf pr_source.tar.gz ubuntu-advantage-client
                 cp pr_source.tar.gz /tmp
                 ls -lh /tmp
                 cd $TRAVIS_BUILD_DIR
                 pwd
              fi
          - sudo apt-get remove --yes --purge lxd lxd-client
          - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - sg lxd -c "UACLIENT_BEHAVE_BUILD_PR=${BUILD_PR} make test"
    - python: 3.7
      env: TOXENV=behave-pro-aws
      script:
          - BUILD_PR=1
          - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then BUILD_PR=0; fi
          - >
              if [ "$BUILD_PR" -eq "1" ]; then
                 cd $TRAVIS_BUILD_DIR/..
                 tar -zcvf pr_source.tar.gz ubuntu-advantage-client
                 cp pr_source.tar.gz /tmp
                 ls -lh /tmp
                 cd $TRAVIS_BUILD_DIR
                 pwd
              fi
          - UACLIENT_BEHAVE_BUILD_PR=${BUILD_PR} make test
    - env:
        PACKAGE_BUILD_SERIES=trusty
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
    - env:
        PACKAGE_BUILD_SERIES=xenial
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
    - env:
        PACKAGE_BUILD_SERIES=bionic
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
    - env:
        PACKAGE_BUILD_SERIES=eoan
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
    - env:
        PACKAGE_BUILD_SERIES=focal
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
    - python: 3.4
      env: TOXENV=py3-trusty,flake8-trusty
      dist: trusty
    - python: 3.5
      env: TOXENV=py3-xenial,flake8-xenial
      dist: xenial
    - python: 3.6
      env: TOXENV=py3-bionic,flake8-bionic
    - python: 3.7
      env: TOXENV=py3-eoan,flake8-eoan
    - python: 3.8
      env: TOXENV=py3,flake8
    - python: 3.7
      env: TOXENV=mypy
    - python: 3.7
      env: TOXENV=black
