language: python
dist: bionic

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

jobs:
  include:
    - env:
        PACKAGE_BUILD_SERIES=xenial
      stage: build
      cache:
        - directories:
          - cache-artifacts
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
	    - mkdir -p cache-artifacts
        - cp *deb cache-artifacts/
    - env:
        LMOURA=blah
      stage: cleanup
      cache:
        - directories:
          - cache-artifacts
      script:
        - ls cache-artifacts
