---

name: CI (base)

on:
  push:
  pull_request:

defaults:
  run:
    shell: sh -ex {0}

jobs:
  lint-and-style:
    name: Static Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy install tox
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Formatting
        run: tox -e black -e isort
      - name: Style
        run: tox -e flake8
      - name: Mypy
        run: tox -e mypy
      - name: Version Consistency
        run: python3 ./tools/check-versions-are-consistent.py
      - name: Docs
        run: tox -e docs
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy install tox
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Unit
        run: tox -e test
